name: loss-shaping
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - pip
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - wandb
  - seaborn
  - tqdm
  - sympy
  - pip:
    - torch==1.9.0
    - reformer_pytorch